BASEDIR = ..

ICON = dosbox.png
README = ../README
BUILD = dosbox
TARGET = dosbox_od.opk
DEFAULT_DESKTOP = default.gcw0.desktop

all: opk

build:
	cd $(BASEDIR) && $(MAKE)

opk: build $(BUILD) $(ICON) $(README) $(DEFAULT_DESKTOP)
	@mksquashfs \
	$(DEFAULT_DESKTOP) \
	dosbox.sh \
	$(README) \
	$(ICON) \
	$(BUILD) \
	$(TARGET) \
	-all-root -noappend -no-exports -no-xattrs

clean:
	cd $(BASEDIR) && $(MAKE) clean
	-rm $(TARGET)
